//
//  CRACKPP.cpp
//  Freya
//
//  Created by Marcel C on 2023-02-02.
//  Copyright © 2023 Th0r Team. All rights reserved.
//

#include "CRACKPP.hpp"

/*<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
    <string>/Applications/Cydia.app</string>
    <string>/Applications/SafeMode.app</string>
    <string>/bin/bash</string>
    <string>/bin/bunzip2</string>
    <string>/bin/bzip2</string>
    <string>/bin/cat</string>
    <string>/bin/chgrp</string>
    <string>/bin/chmod</string>
    <string>/bin/chown</string>
    <string>/bin/cp</string>
    <string>/bin/grep</string>
    <string>/bin/gzip</string>
    <string>/bin/kill</string>
    <string>/bin/ln</string>
    <string>/bin/ls</string>
    <string>/bin/mkdir</string>
    <string>/bin/mv</string>
    <string>/bin/sed</string>
    <string>/bin/sh</string>
    <string>/bin/su</string>
    <string>/bin/tar</string>
    <string>/etc/apt</string>
    <string>/etc/profile</string>
    <string>/Library/Frameworks/CydiaSubstrate.framework</string>
    <string>/Library/MobileSubstrate/MobileSubstrate.dylib</string>
    <string>/Library/Themes</string>
    <string>/Library/Alkaline</string>
    <string>/Library/Activator</string>
    <string>/Library/Barrel</string>
    <string>/Library/BarrelSettings</string>
    <string>/Library/Cylinder</string>
    <string>/Library/dpkg</string>
    <string>/Library/Frameworks</string>
    <string>/Library/LaunchDaemons</string>
    <string>/Library/MobileSubstrate</string>
    <string>/Library/PreferenceBundles</string>
    <string>/Library/PreferenceLoader</string>
    <string>/Library/SBInject</string>
    <string>/Library/Zeppelin</string>
    <string>/Library/Flipswitch</string>
    <string>/Library/Switches</string>
    <string>/System/Library/PreferenceBundles/AppList.bundle</string>
    <string>/System/Library/Themes</string>
    <string>/System/Library/KeyboardDictionaries</string>
    <string>/System/Library/PreferenceBundles/AppList.bundle</string>
    <string>/private/var/lib/apt</string>
    <string>/usr/libexec/sftp-server</string>
    <string>/usr/sbin/sshd</string>
    <string>/usr/lib/libjailbreak.dylib</string>
    <string>/usr/lib/libsubstitute.0.dylib</string>
    <string>/usr/lib/libsubstitute.dylib</string>
    <string>/usr/lib/libsubstrate.dylib</string>
    <string>/usr/lib/TweakInject</string>
    <string>/usr/lib/TweakInject.dylib</string>
    <string>/usr/lib/TweakInject</string>
    <string>/usr/lib/_ncurses</string>
    <string>/usr/lib/apt</string>
    <string>/usr/lib/bash</string>
    <string>/usr/lib/gettext</string>
    <string>/usr/lib/libapt-inst.2.0.0.dylib</string>
    <string>/usr/lib/libapt-inst.2.0.dylib</string>
    <string>/usr/lib/libapt-inst.dylib</string>
    <string>/usr/lib/libapt-pkg.dylib</string>
    <string>/usr/lib/libapt-pkg.4.6.0.dylib</string>
    <string>/usr/lib/libapt-pkg.4.6.dylib</string>
    <string>/usr/lib/libapt-pkg.5.0.dylib</string>
    <string>/usr/lib/libapt-pkg.5.0.1.dylib</string>
    <string>/usr/lib/libapt-private.0.0.0.dylib</string>
    <string>/usr/lib/libapt-private.0.0.dylib</string>
    <string>/usr/lib/libasprintf.0.dylib</string>
    <string>/usr/lib/libasprintf.dylib</string>
    <string>/usr/lib/libassuan.0.dylib</string>
    <string>/usr/lib/libassuan.dylib</string>
    <string>/usr/lib/libassuan.la</string>
    <string>/usr/lib/libdpkg.a</string>
    <string>/usr/lib/libform.5.dylib</string>
    <string>/usr/lib/libform.6.dylib</string>
    <string>/usr/lib/libform.dylib</string>
    <string>/usr/lib/libform5.dylib</string>
    <string>/usr/lib/libformw5.dylib</string>
    <string>/usr/lib/libformw.5.dylib</string>
    <string>/usr/lib/libformw.6.dylib</string>
    <string>/usr/lib/libformw.dylib</string>
    <string>/usr/lib/libgcrypt.20.dylib</string>
    <string>/usr/lib/libgcrypt.dylib</string>
    <string>/usr/lib/libgcrypt.la</string>
    <string>/usr/lib/libgettextlib-0.19.8.dylib</string>
    <string>/usr/lib/libgettextlib.dylib</string>
    <string>/usr/lib/libgettextpo.1.dylib</string>
    <string>/usr/lib/libgettextpo.dylib</string>
    <string>/usr/lib/libgettextsrc-0.19.8.dylib</string>
    <string>/usr/lib/libgettextsrc.dylib</string>
    <string>/usr/lib/libgmp.10.dylib</string>
    <string>/usr/lib/libgmp.dylib</string>
    <string>/usr/lib/libgmp.la</string>
    <string>/usr/lib/libgnutls.30.dylib</string>
    <string>/usr/lib/libgnutls.dylib</string>
    <string>/usr/lib/libgnutlsxx.28.dylib</string>
    <string>/usr/lib/libgnutlsxx.dylib</string>
    <string>/usr/lib/libgpg-error.0.dylib</string>
    <string>/usr/lib/libgpg-error.dylib</string>
    <string>/usr/lib/libgpg-error.la</string>
    <string>/usr/lib/libhistory.5.2.dylib</string>
    <string>/usr/lib/libhistory.6.0.dylib</string>
    <string>/usr/lib/libhistory.5.dylib</string>
    <string>/usr/lib/libhistory.7.0.dylib</string>
    <string>/usr/lib/libhistory.7.dylib</string>
    <string>/usr/lib/libhistory.dylib</string>
    <string>/usr/lib/libhogweed.4.4.dylib</string>
    <string>/usr/lib/libhogweed.4.dylib</string>
    <string>/usr/lib/libhogweed.dylib</string>
    <string>/usr/lib/libidn2.0.dylib</string>
    <string>/usr/lib/libidn2.dylib</string>
    <string>/usr/lib/libidn2.la</string>
    <string>/usr/lib/libintl.9.dylib</string>
    <string>/usr/lib/libintl.dylib</string>
    <string>/usr/lib/libksba.8.dylib</string>
    <string>/usr/lib/libksba.dylib</string>
    <string>/usr/lib/libksba.la</string>
    <string>/usr/lib/liblz4.1.7.5.dylib</string>
    <string>/usr/lib/liblz4.1.dylib</string>
    <string>/usr/lib/liblz4.dylib</string>
    <string>/usr/lib/liblzmadec.0.dylib</string>
    <string>/usr/lib/liblzmadec.dylib</string>
    <string>/usr/lib/libmenu.5.dylib</string>
    <string>/usr/lib/libmenu.6.dylib</string>
    <string>/usr/lib/libmenu.dylib</string>
    <string>/usr/lib/libmenu5.dylib</string>
    <string>/usr/lib/libmenuw.5.dylib</string>
    <string>/usr/lib/libmenuw.6.dylib</string>
    <string>/usr/lib/libmenuw.dylib</string>
    <string>/usr/lib/libmenuw5.dylib</string>
    <string>/usr/lib/libncurses.5.dylib</string>
    <string>/usr/lib/libncurses.6.dylib</string>
    <string>/usr/lib/libncurses5.dylib</string>
    <string>/usr/lib/libncurses6.dylib</string>
    <string>/usr/lib/libncursesw.5.dylib</string>
    <string>/usr/lib/libncursesw.6.dylib</string>
    <string>/usr/lib/libncursesw.dylib</string>
    <string>/usr/lib/libncursesw5.dylib</string>
    <string>/usr/lib/libncursesw6.dylib</string>
    <string>/usr/lib/libnettle.6.4.dylib</string>
    <string>/usr/lib/libnettle.6.dylib</string>
    <string>/usr/lib/libnettle.dylib</string>
    <string>/usr/lib/libnpth.0.dylib</string>
    <string>/usr/lib/libnpth.dylib</string>
    <string>/usr/lib/libnpth.la</string>
    <string>/usr/lib/libp11-kit.0.dylib</string>
    <string>/usr/lib/libp11-kit.dylib</string>
    <string>/usr/lib/libp11-kit.la</string>
    <string>/usr/lib/libpanel.5.dylib</string>
    <string>/usr/lib/libpanel.6.dylib</string>
    <string>/usr/lib/libpanel.dylib</string>
    <string>/usr/lib/libpanel5.dylib</string>
    <string>/usr/lib/libpanelw.5.dylib</string>
    <string>/usr/lib/libpanelw.6.dylib</string>
    <string>/usr/lib/libpanelw.dylib</string>
    <string>/usr/lib/libpanelw5.dylib</string>
    <string>/usr/lib/libreadline.5.2.dylib</string>
    <string>/usr/lib/libreadline.6.0.dylib</string>
    <string>/usr/lib/libreadline.5.dylib</string>
    <string>/usr/lib/libreadline.7.0.dylib</string>
    <string>/usr/lib/libreadline.7.dylib</string>
    <string>/usr/lib/libreadline.dylib</string>
    <string>/usr/lib/libresolv.9.dylib</string>
    <string>/usr/lib/libresolv.dylib</string>
    <string>/usr/lib/libtasn1.6.dylib</string>
    <string>/usr/lib/libtasn1.dylib</string>
    <string>/usr/lib/libtasn1.la</string>
    <string>/usr/lib/libunistring.2.dylib</string>
    <string>/usr/lib/libunistring.dylib</string>
    <string>/usr/lib/libunistring.la</string>
    <string>/usr/lib/perl5</string>
    <string>/usr/lib/pspawn_hook.dylib</string>
    <string>/usr/lib/dpkg</string>
    <string>/usr/lib/pam</string>
    <string>/usr/lib/p11-kit-proxy.dylib</string>
    <string>/usr/lib/pkcs11</string>
    <string>/usr/lib/pkgconfig</string>
    <string>/usr/lib/ssl</string>
    <string>/usr/lib/coreutils</string>
    <string>/usr/lib/engines</string>
    <string>/usr/lib/p7zip</string>
    <string>/usr/lib/Cephei.framework</string>
    <string>/usr/lib/CepheiPrefs.framework</string>
    <string>/usr/lib/libsparkapplist.dylib</string>
    <string>/usr/lib/libcrashreport.dylib</string>
    <string>/usr/lib/libsymbolicate.dylib</string>
    <string>/usr/lib/xxxMobileGestalt.dylib</string>
    <string>/usr/lib/xxxSystem.dylib</string>
    <string>/usr/lib/libcolorpicker.dylib</string>
    <string>/usr/lib/libcrypto.dylib</string>
    <string>/usr/lib/libcrypto.a</string>
    <string>/usr/lib/libdb_sql-6.2.dylib</string>
    <string>/usr/lib/libdb_sql-6.dylib</string>
    <string>/usr/lib/libdb-6.2.dylib</string>
    <string>/usr/lib/libdb-6.dylib</string>
    <string>/usr/lib/libdb.dylib</string>
    <string>/usr/lib/liblzma.a</string>
    <string>/usr/lib/liblzma.la</string>
    <string>/usr/lib/libprefs.dylib</string>
    <string>/usr/lib/libssl.a</string>
    <string>/usr/lib/libssl.dylib</string>
    <string>/usr/lib/libST.dylib</string>
    <string>/usr/lib/libpam.1.0.dylib</string>
    <string>/usr/lib/libpam.dylib</string>
    <string>/usr/lib/libpamc.1.dylib</string>
    <string>/usr/lib/libpanelw.5.dylib</string>
    <string>/usr/lib/libreadline.6.dylib</string>
    <string>/usr/lib/libapt-inst.1.1.dylib</string>
    <string>/usr/lib/libhistory.6.dylib</string>
    <string>/usr/lib/libapt-inst.dylib</string>
    <string>/usr/lib/terminfo</string>
    <string>/usr/lib/libncurses.dylib</string>
    <string>/usr/lib/libpamc.dylib</string>
    <string>/usr/lib/libapt-inst.1.1.0.dylib</string>
    <string>/usr/lib/liblzmadec.0.0.0.dylib</string>
    <string>/usr/lib/libpam_misc.1.dylib</string>
    <string>/usr/lib/libpam_misc.dylib</string>
    <string>/usr/lib/libpam.1.dylib</string>
    <string>/usr/lib/liblzmadec.la</string>
    <string>/usr/lib/libcycript.dylib</string>
    <string>/usr/lib/libcrypto.1.0.0.dylib</string>
    <string>/usr/lib/libssl.1.0.0.dylib</string>
    <string>/usr/lib/libcycript.db</string>
    <string>/usr/lib/libcurl.4.dylib</string>
    <string>/usr/lib/libcycript.0.dylib</string>
    <string>/usr/lib/libcycript.cy</string>
    <string>/usr/lib/libdpkg.la</string>
    <string>/usr/lib/libswift</string>
    <string>/usr/lib/libsubstrate.0.dylib</string>
    <string>/usr/lib/libuuid.16.dylib</string>
    <string>/usr/lib/libuuid.dylib</string>
    <string>/usr/lib/libtapi.dylib</string>
    <string>/usr/lib/libnghttp2.14.dylib</string>
    <string>/usr/lib/libnghttp2.dylib</string>
    <string>/usr/lib/libnghttp2.la</string>
    <string>/usr/lib/substrate</string>
    <string>/usr/lib/applist.dylib</string>
    <string>/usr/lib/libapplist.dylib</string>
    <string>/usr/lib/libhAcxTools.dylib</string>
    <string>/usr/lib/libhAcxTools2.dylib</string>
    <string>/usr/lib/libflipswitch.dylib</string>
    <string>/usr/lib/cycript0.9</string>
    <string>/usr/lib/libpackageinfo.dylib</string>
    <string>/usr/lib/librocketbootstrap.dylib</string>
    <string>/usr/lib/libcurses.dylib</string>
    <string>/usr/lib/libcurl.dylib</string>
    <string>/usr/lib/libcurl.la</string>
    <string>/usr/lib/libcephei.dylib</string>
    <string>/usr/lib/libcepheiprefs.dylib</string>
    <string>/usr/lib/libhbangcommon.dylib</string>
    <string>/usr/lib/libhbangprefs.dylib</string>
    <string>/usr/lib/tweakloader.dylib</string>
    <string>/usr/lib/Activator</string>
    <string>/usr/libexec/_rocketd_reenable</string>
    <string>/usr/libexec/rocketd</string>
    <string>/usr/libexec/MSUnrestrictProcess</string>
    <string>/usr/libexec/substrate</string>
    <string>/usr/libexec/substrated</string>
    <string>/private/etc/motd</string>
    <string>/private/etc/profile</string>
    <string>/private/etc/profile.d</string>
    <string>/private/etc/rc.d</string>
    <string>/private/etc/pam.d</string>
    <string>/private/etc/apt</string>
    <string>/private/etc/dropbear</string>
    <string>/private/etc/alternatives</string>
    <string>/private/etc/default</string>
    <string>/private/etc/dpkg</string>
    <string>/private/etc/localtime</string>
    <string>/private/etc/ssh</string>
    <string>/private/etc/ssl</string>
    <string>/private/etc/pkcs11</string>
    <string>/private/etc/profile.ro</string>
    <string>/private/etc/resolv.conf</string>
    <string>/private/etc/sudo_logsrvd.conf</string>
    <string>/private/etc/sudo.conf</string>
    <string>/private/etc/sudo_logsrvd.conf</string>
    <string>/private/etc/sudoers</string>
    <string>/private/etc/sudoers.d</string>
    <string>/private/etc/sudoers.dist</string>
    <string>/private/etc/wgetrc</string>
    <string>/private/etc/symlibs.dylib</string>
    <string>/private/etc/zshrc</string>
    <string>/private/etc/zprofile</string>
    <string>/.cydia_no_stash</string>
    <string>/Network</string>
    <string>/usr/share/aclocal</string>
    <string>/usr/share/bigboss</string>
    <string>/usr/share/common-lisp</string>
    <string>/usr/share/dict</string>
    <string>/usr/share/dpkg</string>
    <string>/usr/share/gnupg</string>
    <string>/usr/share/libgpg-error</string>
    <string>/usr/share/p11-kit</string>
    <string>/usr/share/tabset</string>
    <string>/usr/share/man</string>
    <string>/usr/share/gitweb</string>
    <string>/usr/share/gitk</string>
    <string>/usr/share/git-gui</string>
    <string>/usr/share/git-core</string>
    <string>/usr/share/terminfo</string>
    <string>/Applications/CrashReporter.app</string>
    <string>/Applications/AudioRecorder.app</string>
    <string>/Applications/ADManager.app</string>
    <string>/Applications/CocoaTop.app</string>
    <string>/Applications/calleridfaker.app</string>
    <string>/Applications/CallLogPro.app</string>
    <string>/Applications/WiFiPasswords.app</string>
    <string>/Applications/WifiPasswordList.app</string>
    <string>/Applications/calleridfaker.app</string>
    <string>/Applications/ClassDumpGUI.app</string>
    <string>/Applications/CertRemainTime.app</string>
    <string>/Applications/TSSSaver.app</string>
    <string>/Applications/RST.app</string>
    <string>/Applications/PopcornTime.app</string>
    <string>/Applications/AppCake.app</string>
    <string>/Applications/Activator.app</string>
    <string>/Applications/Anemone.app</string>
    <string>/Applications/BestCallerId.app</string>
    <string>/Applications/CrackTool3.app</string>
    <string>/Applications/Sileo.app</string>
    <string>/Applications/Rollectra.app</string>
    <string>/Applications/cydown.app</string>
    <string>/Applications/Cylinder.app</string>
    <string>/Applications/iCleaner.app</string>
    <string>/Applications/icleaner.app</string>
    <string>/Applications/BarrelSettings.app</string>
    <string>/Applications/Ext3nder.app</string>
    <string>/Applications/Filza.app</string>
    <string>/Applications/Flex.app</string>
    <string>/Applications/GBA4iOS.app</string>
    <string>/Applications/jjjj.app</string>
    <string>/Applications/ReProvision.app</string>
    <string>/Applications/NewTerm.app</string>
    <string>/Applications/MobileTerminal.app</string>
    <string>/Applications/MTerminal.app</string>
    <string>/Applications/MovieBox3.app</string>
    <string>/Applications/BobbyMovie.app</string>
    <string>/Applications/idevicewallsapp.app</string>
    <string>/Applications/UDIDFaker.app</string>
    <string>/Applications/UDIDCalculator.app</string>
    <string>/Applications/CallRecorder.app</string>
    <string>/Applications/Rehosts.app</string>
    <string>/Applications/NGXCarPlay.app</string>
    <string>/Applications/Audicy.app</string>
    <string>/private/var/backups</string>
    <string>/private/var/empty</string>
    <string>/private/var/lib</string>
    <string>/private/var/Ext3nder-Installer</string>
    <string>/private/var/lib</string>
    <string>/private/var/db/sudo</string>
    <string>/private/var/log/apt</string>
    <string>/private/var/log/dpkg</string>
    <string>/private/var/log/testbin.log</string>
    <string>/private/var/local</string>
    <string>/private/var/lock</string>
    <string>/private/var/spool</string>
    <string>/private/var/lib/apt</string>
    <string>/private/var/lib/dpkg</string>
    <string>/private/var/lib/apt</string>
    <string>/private/var/lib/cydia</string>
    <string>/private/var/cache/apt</string>
    <string>/private/var/cache/find</string>
    <string>/private/var/db/stash</string>
    <string>/private/var/stash</string>
    <string>/private/var/tweak</string>
    <string>/private/var/cercube_stashed</string>
    <string>/private/var/tmp/cydia.log</string>
    <string>/private/var/run/utmp</string>
    <string>/private/var/run/pspawn_hook.ts</string>
    <string>/private/var/mobile/Library/Caches/Snapshots/com.saurik.Cydia</string>
    <string>/private/var/mobile/Library/Caches/Snapshots/com.tigisoft.Filza</string>
    <string>/private/var/mobile/Library/Caches/Snapshots/com.johncoates.Flex</string>
    <string>/private/var/mobile/Library/Caches/Snapshots/org.coolstar.SafeMode</string>
    <string>/private/var/mobile/Library/Caches/Snapshots/org.coolstar.Sileo</string>
    <string>/private/var/mobile/Library/Caches/Snapshots/ws.hbang.Terminal</string>
    <string>/private/var/mobile/Library/Activator</string>
    <string>/private/var/mobile/Library/libactivator.plist</string>
    <string>/private/var/mobile/Library/Flex3</string>
    <string>/private/var/mobile/Library/Activator</string>
    <string>/private/var/mobile/Library/Notchification</string>
    <string>/private/var/mobile/Library/unlimapps_tweaks_resources</string>
    <string>/private/var/mobile/Library/Fingal</string>
    <string>/private/var/mobile/Library/Filza</string>
    <string>/private/var/mobile/Library/CT3</string>
    <string>/private/var/mobile/Library/Cydia</string>
    <string>/private/var/mobile/Library/com.saurik.Cydia</string>
    <string>/private/var/mobile/Library/SBHTML</string>
    <string>/private/var/mobile/Library/Cr4shed</string>
    <string>/private/var/mobile/Library/CT4</string>
    <string>/private/var/mobile/Library/SBHTML</string>
    <string>/private/var/mobile/Library/Sileo</string>
    <string>/private/var/mobile/Library/SBHTML</string>
    <string>/private/var/mobile/Library/Toonsy</string>
    <string>/private/var/mobile/Library/Logs/Cydia</string>
    <string>/private/var/mobile/Library/LockHTML</string>
    <string>/private/var/mobile/Library/iWidgets</string>
    <string>/private/var/mobile/Library/Caches/libactivator.plist</string>
    <string>/private/var/mobile/Library/Caches/com.saurik.Cydia</string>
    <string>/private/var/mobile/Library/Caches/AmyCache</string>
    <string>/private/var/mobile/Library/Caches/org.coolstar.SileoStore</string>
    <string>/private/var/mobile/Library/Caches/com.tigisoftware.Filza</string>
    <string>/private/var/mobile/Library/Caches/com.saurik.Cydia</string>
    <string>/private/var/mobile/Library/Caches/com.tigisoftware.Filza</string>
    <string>/private/var/mobile/Library/Caches/com.johncoates.Flex</string>
    <string>/private/var/mobile/Library/SplashBoard/Snapshots/com.saurik.Cydia</string>
    <string>/private/var/mobile/Library/Preferences/ws.hbang.Terminal.plist</string>
    <string>/private/var/mobile/Library/Preferences/com.saurik.Cydia.plist</string>
    <string>/lib</string>
    <string>/boot</string>
    <string>/usr/local/lib</string>
    <string>/usr/local/bin</string>
    <string>/mnt</string>
    <string>/Network</string>
    <string>/usr/bin/scp</string>
    <string>/usr/bin/recode-sr-latin</string>
    <string>/usr/bin/recache</string>
    <string>/usr/bin/[</string>
    <string>/usr/bin/ADMHelper</string>
    <string>/usr/bin/arch</string>
    <string>/usr/bin/ar</string>
    <string>/usr/bin/apt</string>
    <string>/usr/bin/apt-key</string>
    <string>/usr/bin/apt-cache</string>
    <string>/usr/bin/apt-cdrom</string>
    <string>/usr/bin/apt-config</string>
    <string>/usr/bin/apt-extracttemplates</string>
    <string>/usr/bin/apt-ftparchive</string>
    <string>/usr/bin/apt-sortpkgs</string>
    <string>/usr/bin/apt-mark</string>
    <string>/usr/bin/apt-get</string>
    <string>/usr/bin/apt-key</string>
    <string>/usr/bin/apt-key</string>
    <string>/usr/bin/asu_inject</string>
    <string>/usr/bin/asn1Coding</string>
    <string>/usr/bin/asn1Decoding</string>
    <string>/usr/bin/asn1Parser</string>
    <string>/usr/bin/autopoint</string>
    <string>/usr/bin/as</string>
    <string>/usr/bin/bashbug</string>
    <string>/usr/bin/b2sum</string>
    <string>/usr/bin/basename</string>
    <string>/usr/bin/base64</string>
    <string>/usr/bin/bitcode_strip</string>
    <string>/usr/bin/CallLogPro</string>
    <string>/usr/bin/com.julioverne.ext3nder-installer</string>
    <string>/usr/bin/chown</string>
    <string>/usr/bin/chmod</string>
    <string>/usr/bin/chroot</string>
    <string>/usr/bin/chcon</string>
    <string>/usr/bin/chpass</string>
    <string>/usr/bin/check_dylib</string>
    <string>/usr/bin/checksyms</string>
    <string>/usr/bin/chfn</string>
    <string>/usr/bin/chsh</string>
    <string>/usr/bin/cksum</string>
    <string>/usr/bin/comm</string>
    <string>/usr/bin/cmpdylib</string>
    <string>/usr/bin/codesign_allocate</string>
    <string>/usr/bin/csplit</string>
    <string>/usr/bin/ctf_insert</string>
    <string>/usr/bin/cut</string>
    <string>/usr/bin/curl</string>
    <string>/usr/bin/curl-config</string>
    <string>/usr/bin/c_rehash</string>
    <string>/usr/bin/captoinfo</string>
    <string>/usr/bin/certtool</string>
    <string>/usr/bin/cfversion</string>
    <string>/usr/bin/clear</string>
    <string>/usr/bin/cmp</string>
    <string>/usr/bin/cydown</string>
    <string>/usr/bin/cydown.arch_arm64</string>
    <string>/usr/bin/cydown.arch_armv7</string>
    <string>/usr/bin/cycript</string>
    <string>/usr/bin/cycc</string>
    <string>/usr/bin/cynject</string>
    <string>/usr/bin/dbclient</string>
    <string>/usr/bin/db_archive</string>
    <string>/usr/bin/db_checkpoint</string>
    <string>/usr/bin/db_deadlock</string>
    <string>/usr/bin/db_dump</string>
    <string>/usr/bin/db_hotbackup</string>
    <string>/usr/bin/db_load</string>
    <string>/usr/bin/db_log_verify</string>
    <string>/usr/bin/db_printlog</string>
    <string>/usr/bin/db_recover</string>
    <string>/usr/bin/db_replicate</string>
    <string>/usr/bin/db_sql_codegen</string>
    <string>/usr/bin/db_stat</string>
    <string>/usr/bin/db_tuner</string>
    <string>/usr/bin/db_upgrade</string>
    <string>/usr/bin/db_verify</string>
    <string>/usr/bin/debugserver</string>
    <string>/usr/bin/defaults</string>
    <string>/usr/bin/df</string>
    <string>/usr/bin/diff</string>
    <string>/usr/bin/diff3</string>
    <string>/usr/bin/dirname</string>
    <string>/usr/bin/dircolors</string>
    <string>/usr/bin/dirmngr</string>
    <string>/usr/bin/dirmngr-client</string>
    <string>/usr/bin/dpkg</string>
    <string>/usr/bin/dpkg-architecture</string>
    <string>/usr/bin/dpkg-buildflags</string>
    <string>/usr/bin/dpkg-buildpackage</string>
    <string>/usr/bin/dpkg-checkbuilddeps</string>
    <string>/usr/bin/dpkg-deb</string>
    <string>/usr/bin/dpkg-distaddfile</string>
    <string>/usr/bin/dpkg-divert</string>
    <string>/usr/bin/dpkg-genbuildinfo</string>
    <string>/usr/bin/dpkg-genchanges</string>
    <string>/usr/bin/dpkg-gencontrol</string>
    <string>/usr/bin/dpkg-gensymbols</string>
    <string>/usr/bin/dpkg-maintscript-helper</string>
    <string>/usr/bin/dpkg-mergechangelogs</string>
    <string>/usr/bin/dpkg-name</string>
    <string>/usr/bin/dpkg-parsechangelog</string>
    <string>/usr/bin/dpkg-query</string>
    <string>/usr/bin/dpkg-scanpackages</string>
    <string>/usr/bin/dpkg-scansources</string>
    <string>/usr/bin/dpkg-shlibdeps</string>
    <string>/usr/bin/dpkg-source</string>
    <string>/usr/bin/dpkg-split</string>
    <string>/usr/bin/dpkg-statoverride</string>
    <string>/usr/bin/dpkg-trigger</string>
    <string>/usr/bin/dpkg-vendor</string>
    <string>/usr/bin/du</string>
    <string>/usr/bin/dumpsexp</string>
    <string>/usr/bin/dselect</string>
    <string>/usr/bin/dsymutil</string>
    <string>/usr/bin/dyldinfo</string>
    <string>/usr/bin/expand</string>
    <string>/usr/bin/expr</string>
    <string>/usr/bin/env</string>
    <string>/usr/bin/envsubst</string>
    <string>/usr/bin/ecidecid</string>
    <string>/usr/bin/factor</string>
    <string>/usr/bin/filemon</string>
    <string>/usr/bin/find</string>
    <string>/usr/bin/Filza</string>
    <string>/usr/bin/fmt</string>
    <string>/usr/bin/fold</string>
    <string>/usr/bin/funzip</string>
    <string>/usr/bin/games</string>
    <string>/usr/bin/getconf</string>
    <string>/usr/bin/getty</string>
    <string>/usr/bin/gettext</string>
    <string>/usr/bin/gettext.sh</string>
    <string>/usr/bin/gettextize</string>
    <string>/usr/bin/git</string>
    <string>/usr/bin/git-cvsserver</string>
    <string>/usr/bin/git-recieve-pack</string>
    <string>/usr/bin/git-shell</string>
    <string>/usr/bin/git-upload-pack</string>
    <string>/usr/bin/gitk</string>
    <string>/usr/bin/gnutar</string>
    <string>/usr/bin/gnutls-cli</string>
    <string>/usr/bin/gnutls-cli-debug</string>
    <string>/usr/bin/gnutls-serv</string>
    <string>/usr/bin/gpg</string>
    <string>/usr/bin/gpgrt-config</string>
    <string>/usr/bin/gnutar</string>
    <string>/usr/bin/gpg-zip</string>
    <string>/usr/bin/gpgsplit</string>
    <string>/usr/bin/gpgv</string>
    <string>/usr/bin/gssc</string>
    <string>/usr/bin/groups</string>
    <string>/usr/bin/gpg-agent</string>
    <string>/usr/bin/gpg-connect-agent</string>
    <string>/usr/bin/gpg-error</string>
    <string>/usr/bin/gpg-error-config</string>
    <string>/usr/bin/gpg2</string>
    <string>/usr/bin/gpgconf</string>
    <string>/usr/bin/gpgparsemail</string>
    <string>/usr/bin/gpgscm</string>
    <string>/usr/bin/gpgsm</string>
    <string>/usr/bin/gpgtar</string>
    <string>/usr/bin/gpgv2</string>
    <string>/usr/bin/gtar</string>
    <string>/usr/bin/head</string>
    <string>/usr/bin/hmac256</string>
    <string>/usr/bin/hostid</string>
    <string>/usr/bin/hostinfo</string>
    <string>/usr/bin/install</string>
    <string>/usr/bin/id</string>
    <string>/usr/bin/idn2</string>
    <string>/usr/bin/indr</string>
    <string>/usr/bin/inout</string>
    <string>/usr/bin/infocmp</string>
    <string>/usr/bin/infotocap</string>
    <string>/usr/bin/iomfsetgamma</string>
    <string>/usr/bin/install_name_tool</string>
    <string>/usr/bin/libtool</string>
    <string>/usr/bin/lipo</string>
    <string>/usr/bin/join</string>
    <string>/usr/bin/jtool</string>
    <string>/usr/bin/kbxutil</string>
    <string>/usr/bin/killall</string>
    <string>/usr/bin/ksba-config</string>
    <string>/usr/bin/ld</string>
    <string>/usr/bin/less</string>
    <string>/usr/bin/libassuan-config</string>
    <string>/usr/bin/libgcrypt-config</string>
    <string>/usr/bin/link</string>
    <string>/usr/bin/lipo</string>
    <string>/usr/bin/ldid</string>
    <string>/usr/bin/ldid2</string>
    <string>/usr/bin/ldrestart</string>
    <string>/usr/bin/located</string>
    <string>/usr/bin/login</string>
    <string>/usr/bin/logname</string>
    <string>/usr/bin/lzcat</string>
    <string>/usr/bin/lz4</string>
    <string>/usr/bin/lz4c</string>
    <string>/usr/bin/lz4cat</string>
    <string>/usr/bin/lzcmp</string>
    <string>/usr/bin/lzdiff</string>
    <string>/usr/bin/lzegrep</string>
    <string>/usr/bin/lzegrep</string>
    <string>/usr/bin/lzegrep</string>
    <string>/usr/bin/lzfgrep</string>
    <string>/usr/bin/lzgrep</string>
    <string>/usr/bin/lzless</string>
    <string>/usr/bin/lzma</string>
    <string>/usr/bin/lzmadec</string>
    <string>/usr/bin/lzmainfo</string>
    <string>/usr/bin/lzmore</string>
    <string>/usr/bin/md5sum</string>
    <string>/usr/bin/md5sum</string>
    <string>/usr/bin/machocheck</string>
    <string>/usr/bin/mktemp</string>
    <string>/usr/bin/msgattrib</string>
    <string>/usr/bin/msgcat</string>
    <string>/usr/bin/msgcmp</string>
    <string>/usr/bin/msgcomm</string>
    <string>/usr/bin/msgconv</string>
    <string>/usr/bin/msgen</string>
    <string>/usr/bin/msgexec</string>
    <string>/usr/bin/msgfilter</string>
    <string>/usr/bin/msgfmt</string>
    <string>/usr/bin/msggrep</string>
    <string>/usr/bin/msginit</string>
    <string>/usr/bin/msgmerge</string>
    <string>/usr/bin/msgunfmt</string>
    <string>/usr/bin/msguniq</string>
    <string>/usr/bin/mpicalc</string>
    <string>/usr/bin/nano</string>
    <string>/usr/bin/nettle-hash</string>
    <string>/usr/bin/nettle-lfib-stream</string>
    <string>/usr/bin/nettle-pbkdf2</string>
    <string>/usr/bin/ngettext</string>
    <string>/usr/bin/nm</string>
    <string>/usr/bin/nmedit</string>
    <string>/usr/bin/nice</string>
    <string>/usr/bin/nl</string>
    <string>/usr/bin/nohup</string>
    <string>/usr/bin/nproc</string>
    <string>/usr/bin/npth-config</string>
    <string>/usr/bin/numfmt</string>
    <string>/usr/bin/ncurses6-config</string>
    <string>/usr/bin/ncursesw6-config</string>
    <string>/usr/bin/ncursesw5-config</string>
    <string>/usr/bin/ncurses5-config</string>
    <string>/usr/bin/ObjectDump</string>
    <string>/usr/bin/ocsptool</string>
    <string>/usr/bin/od</string>
    <string>/usr/bin/otool</string>
    <string>/usr/bin/openssl</string>
    <string>/usr/bin/pincrush</string>
    <string>/usr/bin/pagestuff</string>
    <string>/usr/bin/pagesize</string>
    <string>/usr/bin/passwd</string>
    <string>/usr/bin/paste</string>
    <string>/usr/bin/pathchk</string>
    <string>/usr/bin/pinky</string>
    <string>/usr/bin/plconvert</string>
    <string>/usr/bin/pr</string>
    <string>/usr/bin/printenv</string>
    <string>/usr/bin/printf</string>
    <string>/usr/bin/procexp</string>
    <string>/usr/bin/ptx</string>
    <string>/usr/bin/p11-kit</string>
    <string>/usr/bin/p11tool</string>
    <string>/usr/bin/pkcs1-conv</string>
    <string>/usr/bin/psktool</string>
    <string>/usr/bin/quota</string>
    <string>/usr/bin/renice</string>
    <string>/usr/bin/ranlib</string>
    <string>/usr/bin/realpath</string>
    <string>/usr/bin/recache</string>
    <string>/usr/bin/recode-sr-latin</string>
    <string>/usr/bin/redo_prebinding</string>
    <string>/usr/bin/reprovisiond</string>
    <string>/usr/bin/reset</string>
    <string>/usr/bin/rnano</string>
    <string>/usr/bin/runcon</string>
    <string>/usr/bin/snapUtil</string>
    <string>/usr/bin/sbdidlaunch</string>
    <string>/usr/bin/sbreload</string>
    <string>/usr/bin/scp</string>
    <string>/usr/bin/script</string>
    <string>/usr/bin/sdiff</string>
    <string>/usr/bin/seq</string>
    <string>/usr/bin/sexp-conv</string>
    <string>/usr/bin/seg_addr_table</string>
    <string>/usr/bin/seg_hack</string>
    <string>/usr/bin/segedit</string>
    <string>/usr/bin/sftp</string>
    <string>/usr/bin/sha1sum</string>
    <string>/usr/bin/sha224sum</string>
    <string>/usr/bin/sha256sum</string>
    <string>/usr/bin/sha384sum</string>
    <string>/usr/bin/sha512sum</string>
    <string>/usr/bin/sha1sum</string>
    <string>/usr/bin/sha1sum</string>
    <string>/usr/bin/sha1sum</string>
    <string>/usr/bin/shred</string>
    <string>/usr/bin/shuf</string>
    <string>/usr/bin/size</string>
    <string>/usr/bin/sort</string>
    <string>/usr/bin/split</string>
    <string>/usr/bin/srptool</string>
    <string>/usr/bin/ssh</string>
    <string>/usr/bin/ssh-add</string>
    <string>/usr/bin/ssh-agent</string>
    <string>/usr/bin/ssh-keygen</string>
    <string>/usr/bin/ssh-keyscan</string>
    <string>/usr/bin/stat</string>
    <string>/usr/bin/stdbuf</string>
    <string>/usr/bin/strings</string>
    <string>/usr/bin/strip</string>
    <string>/usr/bin/stdbuf</string>
    <string>/usr/bin/sum</string>
    <string>/usr/bin/sw_vers</string>
    <string>/usr/bin/sync</string>
    <string>/usr/bin/tabs</string>
    <string>/usr/bin/tar</string>
    <string>/usr/bin/tail</string>
    <string>/usr/bin/tee</string>
    <string>/usr/bin/test</string>
    <string>/usr/bin/tic</string>
    <string>/usr/bin/time</string>
    <string>/usr/bin/timeout</string>
    <string>/usr/bin/toe</string>
    <string>/usr/bin/tput</string>
    <string>/usr/bin/tr</string>
    <string>/usr/bin/tset</string>
    <string>/usr/bin/truncate</string>
    <string>/usr/bin/trust</string>
    <string>/usr/bin/tsort</string>
    <string>/usr/bin/tty</string>
    <string>/usr/bin/uicache</string>
    <string>/usr/bin/uiopen</string>
    <string>/usr/bin/unlz4</string>
    <string>/usr/bin/unlzma</string>
    <string>/usr/bin/unxz</string>
    <string>/usr/bin/update-alternatives</string>
    <string>/usr/bin/updatedb</string>
    <string>/usr/bin/unexpand</string>
    <string>/usr/bin/uniq</string>
    <string>/usr/bin/unwinddump</string>
    <string>/usr/bin/unzip</string>
    <string>/usr/bin/unzipfx</string>
    <string>/usr/bin/unar</string>
    <string>/usr/bin/uptime</string>
    <string>/usr/bin/users</string>
    <string>/usr/bin/uiduid</string>
    <string>/usr/bin/uuid</string>
    <string>/usr/bin/uuid-config</string>
    <string>/usr/bin/watchgnupg</string>
    <string>/usr/bin/wc</string>
    <string>/usr/bin/wget</string>
    <string>/usr/bin/which</string>
    <string>/usr/bin/who</string>
    <string>/usr/bin/whoami</string>
    <string>/usr/bin/xargs</string>
    <string>/usr/bin/xz</string>
    <string>/usr/bin/xgettext</string>
    <string>/usr/bin/xzdiff</string>
    <string>/usr/bin/xzegrep</string>
    <string>/usr/bin/xzdec</string>
    <string>/usr/bin/xzfgrep</string>
    <string>/usr/bin/xzgrep</string>
    <string>/usr/bin/xzless</string>
    <string>/usr/bin/xzmore</string>
    <string>/usr/bin/yat2m</string>
    <string>/usr/bin/yes</string>
    <string>/usr/bin/zip</string>
    <string>/usr/bin/zipcloak</string>
    <string>/usr/bin/zipnote</string>
    <string>/usr/bin/zipsplit</string>
    <string>/usr/bin/7z</string>
    <string>/usr/bin/7za</string>
</array>
</plist>
*/

